✨ Initial set up
IslasGECI/prioritizator pull request #1
Opened 2021-03-24 20:13 UTC by evaristor

2021-04-07 21:27 UTC, nepito reviewed
Aquí te dejo unos comentarios @evaristor por si quieres ir discutiendo de a poquito.

2021-04-07 21:27 UTC, nepito commented on Dockerfile
> +    pip install git+https://github.com/deepy/glicko2 \
```suggestion
    git+https://github.com/deepy/glicko2 \
```

2021-04-07 21:27 UTC, nepito commented on tests/test_github_api.py
> +    obtained_title = task._get_title()
Aquí es donde podemos utilizar mockear la función `requests.get` y pedir que regrese un diccionario con una llave "title". Eso nos aseguraría que nos regrese sol que esperamos que haga el método `_get_title`. Yo me imagino que un cambio así podría servir:
```suggestion
def requests_get(self):
        return (
            {"title": "desde el imitador"}
        )

    mocker.patch(
        "requests.get", requests_get
    )
    obtained_title = task._get_title()
```

2021-04-07 21:27 UTC, nepito commented on tests/test_github_api.py
> +    task._set_title(expected_title)
Tal vez aquí podamos hacer un espía para ver con cuáles argumentos estamos llamando a la función `requests.patch`. :thinking: pero la función sí funcionará como es debido, es decir sí se conectará a internet.

2021-04-07 21:34 UTC, nepito commented on tests/test_github_api.py
> +    obtained_title = task._get_title()
"Recuerda" que deberás de instalar `pytest-mock` y agregar `mocker` como variable de entrada de la prueba `def test_set_and_get_title(mocker):`

2021-04-07 21:43 UTC, evaristor commented
Muchas gracias por tus comentarios @nepito

2021-06-01 06:38 UTC, nepito requested changes
Listo @evaristor, aquí te va la primera tanda

2021-06-01 06:38 UTC, nepito commented on tests/test_Matcher.py
> +    assert obtained_data_path == expected_data_path
Estás tres líneas son código repetido con las 30-32. Por favor, refactoriza para DRY. Tal vez también puedas agregar la 28 (aunque la 28 la necesitamos en la 29) y la 19.

La función quedaría algo así:
```suggestion
def assert_data_path(matcher, data_path):
    obtained_data_path = matcher.data_path
    expected_data_path = data_path
    assert obtained_data_path == expected_data_path
```

2021-06-01 06:38 UTC, nepito commented on tests/test_Matcher.py
> +    assert expected_white_rating_before == obtained_white_rating_before
Estas líneas se repiten con las 62-67, por favor refactorízalas en una nueva función. Tal vez podría quedar algo así:
```suggestion
def assert_white_rating_before(white_id, expected_white_rating_before):
    white_task = Task(id=white_id).load_from_csv(data_path)
    obtained_white_rating_before = white_task.rating
    expected_white_rating_before = 1000
    assert expected_white_rating_before == obtained_white_rating_before
```

2021-06-01 06:38 UTC, nepito commented on tests/test_Matcher.py
> +    assert expected_black_rating_before == obtained_black_rating_before
Por favor refactoriza estás líneas para hacer una función y no repetir las líneas 43-47.

2021-06-01 06:38 UTC, nepito commented on tests/test_github_api.py
> +    obtained_title = task._get_title()
[Aquí](https://github.com/nepito/clean-enoa/pull/1/files#diff-a9977c909a1236b5452f8ba03a521f6bbd629a84ccec71c9659b120cb58e0c2fR40) es como yo le hice.

2021-07-19 21:53 UTC, xwalls commented
Adjunto checklist de implementación y procedo a incorporar sugerencias de nepo ✌🏽

2022-01-14 19:48 UTC, xwalls commented on tests/test_Matcher.py
> +    assert expected_white_rating_before == obtained_white_rating_before
Me imagino algo asi:
```python
def assert_white_rating_before(white_id, expected_white_rating_before):
    white_task = Task(id=white_id).load_from_csv(data_path)
    obtained_white_rating_before = white_task.rating
    assert expected_white_rating_before == obtained_white_rating_before
```
Pero hay un pequeño inconveniente, y este es que dentro de la misma prueba quedaria un assert que al final requeriria un valor que se obtendria dentro de esta nueva funcion:
Linea 55
`    assert obtained_white_rating_after < obtained_white_rating_before
`
Lo que me hace pensar, podemos regresar este valor al contexto original de la prueba para que continue con su flujo?
__NOTA__:Esto mismo ocurre en dos pruebas distintas pero similares
- test_match_existing_tasks()
- test_match_new_tasks()

definitivamente debemos seguir rebotando ideas, aqui hay oportunidad.

2022-05-17 17:28 UTC, nepito approved these changes
LGTM

2022-05-17 17:29 UTC, merged